### ISSUE TITLE
`exporter` folder is missing `__init__.py`

### ISSUE THREAD

**Issue by wknoben** [pangaea-data-publisher/pangaeapy#12]
This leads to issues with installs directly from GitHub, e.g. ```pip install git+https://github.com/pangaea-data-publisher/pangaeapy```, where subfolder `exporter` is ignored during install. Importing the module with ```from pangaeapy.pandataset import PanDataSet``` leads to a ```ModuleNotFoundError: No module named 'pangaeapy.exporter```.

```pip install pangaeapy``` does not have this issue and import completes successfully. 

Further info:
- ```pip install git+https://github.com/pangaea-data-publisher/pangaeapy``` installs version 0.0.3
- ```pip install pangaeapy``` installs version 0.0.4

**Comment by huberrob** [comment]
I changed setup.py and folder structure, now this should work
