### ISSUE TITLE
PanDataSet.getEventsAsFrame() not exporting Method/Device field

### ISSUE THREAD

**Issue by paradiss1** [pangaea-data-publisher/pangaeapy#15]
When exporting the events of a pangaea dataset, the Method/Device field is returning empty (None).
For instance:

from pangaeapy.pandataset import PanDataSet
ds = PanDataSet('10.1594/PANGAEA.71218')
ds.getEventsAsFrame().device

Returns the events of that dataset, with the column "device" as None's.

**Comment by huberrob** [comment]
Thanks for the hint!
This should be fixed in v.0.0.7 see: https://pypi.org/project/pangaeapy/
