### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by sarah-paradis** [pangaea-data-publisher/pangaeapy#21]
Hi, I'm getting a connection error when trying to access any dataset in PANGAEA. This has been happening for the last couple of weeks and I wasn't sure if it was my internet connection. Seeing how this connection error persists, I wanted to raise this issue here. 

I am getting the following error just by executing these two lines
```
from pangaeapy.src.pandataset import PanDataSet
PanDataSet('10.1594/PANGAEA.57849')
```
````
Traceback (most recent call last):
  File "C:\Users\Python\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Python\venv\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Python\venv\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\Python\venv\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Python\venv\lib\site-packages\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Python\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Python\venv\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\Python\venv\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doi.pangaea.de', port=443): Max retries exceeded with url: /10.1594/PANGAEA.57849?format=citation_text&charset=UTF-8 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Python\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-dcc1b675b247>", line 1, in <module>
    PanDataSet('10.1594/PANGAEA.57849')
  File "C:\Users\Python\venv\lib\site-packages\pangaeapy\src\pandataset.py", line 404, in __init__
    self.setMetadata()
  File "C:\Users\Python\venv\lib\site-packages\pangaeapy\src\pandataset.py", line 746, in setMetadata
    self._setCitation()
  File "C:\Users\Python\venv\lib\site-packages\pangaeapy\src\pandataset.py", line 737, in _setCitation
    r=requests.get(citationURL)
  File "C:\Users\Python\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Python\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Python\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Python\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Python\venv\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='doi.pangaea.de', port=443): Max retries exceeded with url: /10.1594/PANGAEA.57849?format=citation_text&charset=UTF-8 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))

**Comment by huberrob** [comment]
It seems as if you ran into the HTTP 503 or 429 problem. PANGAEA has a built in brake which just allows a certain amount of requests per minute. This is what the ' Max retries exceeded with url' is trying to tell you.
Are you calling pangaeapy Dataset in a loop? Then you should pause the execution a bit.

**Comment by sarah-paradis** [comment]
Hi, thanks for your reply. No, I'm calling pangaeapy once, as shown in the two lines of code. I just tried running again these two lines in another computer and I got the same error.

**Comment by huberrob** [comment]
(Un)fortunately I cannot reproduce the error, please make sure you are using the latest version of  pandataset.py from this Github repo. This version is not yet available via pip so you'll have to replace this file manually.

**Comment by sarah-paradis** [comment]
Thanks for the suggestion. The issue disappears when installing the latest version from github.
By the way, the setup.py may not be up to date: it fails to install because "export" cannot be found in src. I removed that package from setup.py and could install it without problems.

**Comment by sarah-paradis** [comment]
Hi,

I believe I was able to identify the problem today. When I posted this issue, I first tried it on a Windows, and I got the error above. When @huberrob suggested to use the most recent version (from github master). I tried it on an Ubuntu, and it worked, so I thought the issue was solved by using the most recent version. However, I see that this problem persists on Windows machines, probably because the HTTP request may be slightly different accross OS's. The requests package used was version 2.26.0 on both OS's and no other dependency was observed in the error Traceback message (see above). 

@huberrob could you try to reproduce the error on a Windows?
The issue can be easily reproduced on a Windows machine with any recent pangaeapy version (>0.0.4) with the same two lines of code:
```
from pangaeapy.src.pandataset import PanDataSet
PanDataSet('10.1594/PANGAEA.57849')
```

In addition, the setup.py still does not work, since it [requires the package pangaeapy.src.export ](https://github.com/pangaea-data-publisher/pangaeapy/blob/8e72153c7521d719a90098d669e8b097900d9721/setup.py#L7) (which is no longer there).

Furthermore, the current version does not work because the file pandataset.py is [importing a module that is missing](https://github.com/pangaea-data-publisher/pangaeapy/blob/8e72153c7521d719a90098d669e8b097900d9721/pangaeapy/src/pandataset.py#L25).

Hope this information can help solve these problems. Let me know if you need more information.

**Comment by huberrob** [comment]
One of my colleagues had the same problem which could be fixed after upgrading requests to 2.26 . I tried to reproduce the error on my windows machine but failed. Can you please check your installed packages and post the result of 'pip list' here so I can check for differences in our environments.

**Comment by huberrob** [comment]
Dear Sara,
can you try the latest pangaeapy version (0.0.8) from pypi: https://pypi.org/project/pangaeapy I have changed some things and for me it worked on both, Linux and Windows.
Robert

**Comment by sarah-paradis** [comment]
Dear Rob,
Sorry for not replying with this issue earlier. I updated to the latest pangaeapy version (0.0.9). I am using requests 2.26.0.
I have tried this from my university's network and from home, enabling and disabling firewalls (in case the issue was there, I don't know).

**Comment by sarah-paradis** [comment]
Hi again,
After months, I decided to look into this error again. The error with the connection was with accessing the certificate, which Python does this using the certifi package, which I had an old version (2020.XX). After upgrading it to the latest version (2022.5.18.1), it could access Pangaea's certificate. 

Thanks for your time and help. If someone else gets this problem, tell them to upgrade their certifi.
