### ISSUE TITLE
Darwin Core export: wrong observation type for living benthos or infauna

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/pangaeapy#25]
https://issues.pangaea.de/browse/PGI-4773
Darwin Core export gives wrong observation type in case living benthos or infauna is reported in sediment

https://www.gbif.org/dataset/81b78f9a-f762-11e1-a439-00145eb45e9a

**Comment by huberrob** [comment]
Disabled 'Fossil Specimen' for all entries since this only applies to 'Preserved Specimen' aka collection/museum objects (http://rs.tdwg.org/dwc/dwctype/FossilSpecimen). 
Now people suspecting that data is derived from fossil material need to check the DwC geologicalcontextid and decide.

**Comment by CecSve** [comment]
Thank you very much. I recrawled the dataset on GBIF but unfortunately it still shows fossil specimen. I checked the endpoint and it looks like the archive still shows fossil specimen: https://digir.pangaea.de/dwca/get?doi=10.1594/PANGAEA.756784. Maybe the archive needs to be refreshed?

**Comment by huberrob** [comment]
The new code is not yet deployed, some QC steps are still required..

**Comment by huberrob** [comment]
pangaeapy is now updated to 1.0.3 which fixes this issue. New code is deployed on digir.pangaea.de which should fic the GBIF issue @CecSve can you confirm?

**Comment by CecSve** [comment]
Thank you @huberrob - the records now show _human observation_ instead!
