### ISSUE TITLE
downloaded data has no unit

### ISSUE THREAD

**Issue by karieca** [pangaea-data-publisher/pangaeapy#26]
Dear pangaeapy team,

I was wondering whether it is on purpose, that the parameter of a downoaded file don't have a unit. 
Example: 
ds = PanDataSet('10.1594/PANGAEA.890530')
ds.data.columns
Index(['Depth', 'Age', 'DBD', 'TC', 'TN', 'Corg dens', 'Event', 'Latitude',
       'Longitude', 'Elevation'],
      dtype='object')
If I download the same data set via the PANGAEA webpage, short name plus unit is provided.

best wishes,
Kathrin

**Comment by huberrob** [comment]
Hallo Kathrin,
The unit is included but not part of the dataframe column name. You can find it using the PanParam objects which are conatined in the params list:

for param in ds.params.values():
    print(param.unit)

Robert
