### ISSUE TITLE
Allow more recent version of Python Requests

### ISSUE THREAD

**Issue by fspreck-indiscale** [pangaea-data-publisher/pangaeapy#35]
I'm having version conflicts when installing Pangeapy together with another dependency of my projects which requires `requests[socks] 2.28.1` whereas Pangeapy requires `requests~=2.26.0`.  Is there any reason not to upgrade the dependency?

**Comment by huberrob** [comment]
You are right, I think I should change it to requests>=2.26.0

**Comment by fspreck-indiscale** [comment]
Thanks for the quick response, that fixes it for me :-)
