### ISSUE TITLE
Reading Comment information from pangaea dataset

### ISSUE THREAD

**Issue by Hegebf** [pangaea-data-publisher/pangaeapy#42]
I have been looking for a way to read the information given in "Comment" for pangaea datasets (example: https://doi.pangaea.de/10.1594/PANGAEA.800288), but as far as I can see this is not yet possible. 

Is this a feature you are planning on implementing?

**Comment by fspreck-indiscale** [comment]
@huberrob If you're open to community contributions, I could include this in a PR for #41.

**Comment by huberrob** [comment]
Please let me take a look at it first, I was planning to do something with
the JSON handling anyway  I am on travel now.. but of course community
input is welcome
Robert

fspreck-indiscale ***@***.***> schrieb am Fr., 28. Apr. 2023,
11:59:
