### ISSUE TITLE
PANGAEA contact details in dwca exporter

### ISSUE THREAD

**Issue by acwittmann** [pangaea-data-publisher/pangaeapy#43]
Hi,
in the metadata file please add "first name", "last name" and "position" of PANGAEA staff to both the "Resource contacts" and "Metadata providers".
Thanks a lot!
A

**Comment by huberrob** [comment]
Hi Astrid,

unfortunately I cannot remember to which EML  field this applies... <contact> is already there..

Robert

**Comment by acwittmann** [comment]
Hi Robert,
here is an example for the fields in metadata provider, which most likely can also be used in <contact>:
<metadataProvider>
<individualName>
<givenName>Robert</givenName>
<surName>Huber</surName>
</individualName>
<organizationName>
PANGAEA - Data Publisher for Earth &  Environmental Science
</organizationName>
<positionName>Project Manager</positionName>
<address>
<country>GE</country>
</address>
<electronicMailAddress>info@pangaea.de</electronicMailAddress>
</metadataProvider>
Cheers,
Astrid

**Comment by huberrob** [comment]
I think it was 'role' rather than 'positionName' since positionName is defined as "...This field is intended to be used instead of a particular person or full organization name..."
I have also added a scope=system to indicate the role of the contact
