### ISSUE TITLE
Remove incorrect terms "parent" and "child" from API

### ISSUE THREAD

**Issue by uschindler** [pangaea-data-publisher/pangaeapy#45]
This is confusing to users as we "officially" do not use terms like "parent" or "child" for datasets. With preparing our community workshop, we noticed that those terms are used in API and error messages.

As not all collections are parents and for external users a "parent" means nothing and is not a term used outside of PANGAEA, please replace all usage of "parent" by "collection". "Child datasets" are fine from the persepctive of a dataset with an "In:" citation, but from perspective of pangaeapy it makes no difference. So "normal" datasets should be "dataset" not "child".

So all error messages should be like "cannot download datas as it is collection".

**Comment by uschindler** [comment]
Also remove "type" column in dataset ist. "collection" und "dataset":

![image](https://user-images.githubusercontent.com/1005388/236446237-caaedac7-5e5f-4f58-89c5-bf5eb7b987e0.png)

**Comment by huberrob** [comment]
I took this from the XML:
`<md:entry key="hierarchyLevel" value="parent"/>`
Will you also change it there?

**Comment by uschindler** [comment]
The hierrachy level is only used for special type of dependent collections (where parents and childs exist). It is a legacy tag.

The correct way to detect if something is a collection (no download possible) or not is the "collectionType". if it does not exist, the dataset can be downloaded, otherwise it is a collection.

**Comment by uschindler** [comment]
I would also rename "child" in some messages to "dataset".

Childs can only happen for dependent collections (those where the child dataset has "in:" citation). For end user it makes no difference, so I would leave that out completely (together with hierarchy level).
