### ISSUE TITLE
Resolve attribute error preventing PanDataSet from accessing data

### ISSUE THREAD

**Issue by fx-check** [pangaea-data-publisher/pangaeapy#47]
Dear Pangaea team,
having generated a query using PanQuery, I have run into issues accessing numerous data sets using PanDataSet. I am avoiding [issue 27](https://github.com/pangaea-data-publisher/pangaeapy/issues/27) by checking that the data sets I access are of type 'child'.
However, problems persist, with the most common error returned being:
`AttributeError: 'NoneType' object has no attribute 'text'`
Below, I provide a reproducible example. In this query, 43 out of 212 return an error, 155 succeed (the remaining 14 are of type 'parent' and thus aren't tested). Of the 43 failures to return the dataset, only two errors relate to access restrictions, all other are attribute errors.

```
from pangaeapy import panquery as pq
from pangaeapy import PanDataSet as pdset
bb = [-11, 48, -10.5, 48.5]
my_query = pq.PanQuery("method:CTD/Rosette", bbox = bb, limit = 500)
my_query.totalcount
```
Reality check, this should return 212 results:
```my_query.totalcount
successes = 0
errors = 0
for i in range(my_query.totalcount):
  if my_query.result[i]["type"] == 'child':
    # Checks if the data set is a parent data set, in which case we skip it,  
    # only "child" data sets containing actual data matter:
    uid = int(my_query.result[i]["URI"].split('.')[-1])
    try:
      pdset(uid)
      successes += 1
    except Exception as e: 
      print(uid)
      print(e) 
      errors += 1
```
My results are:
`errors`
43
`successes`
155

**Comment by fspreck-indiscale** [comment]
Hi, I stumbled upon the same problem  in 1.0.14.

It was fixed for me in [1.0.15](https://github.com/pangaea-data-publisher/pangaeapy/commit/19ff9c8960f1a3f97e0f8868788f67ee6afef63f) which hasn't made it to PyPi yet.  For the time beeing you could just install pangaeapy from the current master branch of this repo, i.e.,

    * `git clone https://github.com/pangaea-data-publisher/pangaeapy`
    * `cd pangaeapy/src/pangaeapy`
    * `pip install .`
