### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by fspreck-indiscale** [pangaea-data-publisher/pangaeapy#51]
This package is missing a changelog telling users what parts of the API were added, changed, removed, deprecated, fixed...

A good idea would be to follow https://keepachangelog.com/en/1.1.0/ and use [semantic versioning](https://semver.org/).

**Comment by fspreck-indiscale** [comment]
I just experienced again, how helpful this could be:  somewhere between 1.0.16 and 1.0.17 the former child/parent datasets were renamed to datasets/collections, also changing the names of e.g., `PanDataSet.isParent` to `PanDataSet.isCollection`, thus breaking the API.  These kind of changes should be noted in a changelog, and ideally a breaking API change should be denoted more clearly in the package version (cf. samantic versioning, where a breaking API change would cause an increase of the major version. I.e., pangaeapy 1.0.17 would be pangaeapy 2.0.0).

**Comment by fspreck-indiscale** [comment]
If you're interested @huberrob, I could prepare a PR adding the general structure for this; also for #50.

**Comment by huberrob** [comment]
sorry for the inconvenience, shall I bring back the old variables so you can keep your workflow unchanged?  If you do so please also take into account the effect on pypi packages etc.. 
I promise to add some changelog in the future at least for new releases.

**Comment by fspreck-indiscale** [comment]
No worries!  I adapted my scripts to 1.0.17, but re-introducing the old variables (maybe with a `DeprecationWarning`) could maybe help other users who stumble upon this, so probably a good idea.

Sure, I'll try not to break anything. ;-)

**Comment by fspreck-indiscale** [comment]
I started a [PR](https://github.com/pangaea-data-publisher/pangaeapy/pull/55) for this and #50. The changes should make everything adhere to the [PYPA setup tools specifications](https://setuptools.pypa.io/en/latest/userguide/quickstart.html) and should not have any effect (except for adding the README.md as description) on the PyPi package.

**Comment by fspreck-indiscale** [comment]
Completed with merge of #55
