### ISSUE TITLE
Date/Time field not correctly read anymore

### ISSUE THREAD

**Issue by messiem** [pangaea-data-publisher/pangaeapy#53]
I have been reading a dataset (https://doi.org/10.1594/PANGAEA.937536) that includes a Date/Time column. Until recently (at least Aug 30, 2023 but I believe I ran the notebook since), it was correctly read as 2008-04-23T17:15:00 (for the first data point). Now, only the year appears to be read. To reproduce the issue: 
`pandata = pg.PanDataSet('doi:10.1594/PANGAEA.937536')` then `print(pandata.data['Date/Time'][0])` (returns 2008-01-01 00:00:00). 

Thank you!!

**Comment by huberrob** [comment]
Thanks for the hint, I fixed this in the latest commit
If you do not want to wait for an updated version on pypi, please  replace the file pandataset.py in your local environment and it should hopefully correctly work .

**Comment by messiem** [comment]
I just tested it and it works, thank you very much for such a quick fix!
