### ISSUE TITLE
Date/Time field not read correctly if format does not exactly match

### ISSUE THREAD

**Issue by ajutila** [pangaea-data-publisher/pangaeapy#58]
Hi there! 

I think the fix for #53 still fails, when the Date/Time format doesn't strictly follow the given format of `'%Y-%m-%dT%H:%M:%S'`

I have been playing with https://doi.org/10.1594/PANGAEA.924668, i.e. 10-minute averages of Polarstern tracks, where timestamps are given to the minute, not to the second. 

Since PANGAEA follows the ISO8601 standard, and so does pandas (https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html), could the format parameter in [pandataset.py](https://github.com/pangaea-data-publisher/pangaeapy/blob/49a9863f31f3360368dc57257078a6c5c91c682f/src/pangaeapy/pandataset.py#L1050) be replaced with `'ISO8601'` to enable parsing _any_ ISO8601 time string and not only those that have the time down to seconds? Quick test on my own computer would suggest so, but perhaps wider testing is needed.

**Comment by huberrob** [comment]
Excellent suggestion, thanks!
